const ConfigKeys = {
  MRR_VIEW_ID: "MRR_VIEW_ID",
  MRR_X_FIELD_ID: "MRR_X_FIELD_ID",
  MRR_Y_FIELD_ID: "MRR_Y_FIELD_ID",
  BREAKOUT_TYPE_FIELD_ID: "BREAKOUT_TYPE_FIELD_ID",
  BREAKOUT_VALUE_FIELD_ID: "BREAKOUT_VALUE_FIELD_ID",
  BREAKOUT_LABELS_FIELD_ID: "BREAKOUT_LABELS_FIELD_ID",
};

export default ConfigKeys;
